### ISSUE TITLE
支持pug

### ISSUE THREAD

**Issue by lyumg** [ecomfe/san-loader#20]
.san的template指定lang并添加相应的loader后，san-cli仍旧无法编译通过
是不是现在不支持template的lang属性？vue是可以的

**Comment by ksky521** [comment]
我看了一眼：[template.js](https://github.com/ecomfe/san-loader/blob/master/lib/blocks/template.js#L30-L50)

这个应该是支持的，需要你自己写对应loader的resourcequery的，上面的代码，如果template标签配了`lang=pug`，那么query里面应该有`san=&type=template&lang=pug`，你可以按照这个思路试下

**Comment by lyumg** [comment]
> 我看了一眼：[template.js](https://github.com/ecomfe/san-loader/blob/master/lib/blocks/template.js#L30-L50)
> 
> 这个应该是支持的，需要你自己写对应loader的resourcequery的，上面的代码，如果template标签配了`lang=pug`，那么query里面应该有`san=&type=template&lang=pug`，你可以按照这个思路试下

query是`san=&type=template&lang=pug`，而且 `template lang='pug'` 里面的内容也被编译成了html格式，然后就编译失败了。
```
 * ./node_modules/pug-html-loader/lib/index.js
 * ./node_modules/san-loader/index.js
You may need an additional loader to handle the result of these loaders.
> <div>1213</div>
```
报错是要我添加其他的loader，可是我有些不大明白了，请指教

**Comment by ksky521** [comment]
看我最新的提交：https://github.com/ecomfe/san-loader/commit/6cec4e1561c6d8a4305e774610e91e0227c986fc

**Comment by lyumg** [comment]
> 看我最新的提交：[6cec4e1](https://github.com/ecomfe/san-loader/commit/6cec4e1561c6d8a4305e774610e91e0227c986fc)

先谢谢您的demo，单独的搭建我这边也是可以的。
我这边使用的是san-cli创建的工程，然后通过chainWebpack添加的loader，然后才报的上述的错误

**Comment by ksky521** [comment]
1. cli还有个`configWebpack`可以直接写webpack.config，然后用webpack-merge起来；
2. 你可以建个最小项目，发链接过来，我们看看是什么问题

**Comment by lyumg** [comment]
好了，可以了，感谢您的细心帮助
通过chainWebpack转换后没有html-loader而导致的
使用configWebpack解决了，再次感谢
