### ISSUE TITLE
san单文件组件行内样式的写法在生产模式下无效

### ISSUE THREAD

**Issue by liicos** [ecomfe/san-loader#24]
环境：webpack+san-loader 0.2.0
`<div class="bottom-panel-component panel-component" style="height:{{height}};">`
.san单文件，这种写法在开发模式下可以用，build之后就不能用了，style="height:{{height}};"不生效

**Comment by Lohoyo** [comment]
开发者下午好。
我们尝试复现了该问题，但是发现行内样式在生产模式下也有效，所以，你是否方便提供下能复现该问题的demo？
另外，如果你有兴趣，也可以看下我们用于尝试复现的demo：
https://github.com/Lohoyo/san-loader/tree/issues-24/examples
按照examples文件夹下的README把examples跑起来就可以看到效果。

**Comment by liicos** [comment]
你好，你们复现的代码我跑不起来 (win10  +  node v12.16.2)，我把我的问题也精简了一下代码，搞了一个demo：
https://github.com/liicos/san-loader-issues-24

**Comment by Lohoyo** [comment]
我给你的 demo 提了 1 个 pr，解决办法在[这个 pr ](https://github.com/liicos/san-loader-issues-24/pull/1)里，可以再试试。
问题原因：html-loader 最新版本在生产环境（production）会默认开启 minimize，会导致 san 解析 template 失败，所以使用 html-loader 的时候建议关闭 minimize。详见 [san-loader 文档](https://github.com/ecomfe/san-loader#%E5%8D%95%E6%96%87%E4%BB%B6%E5%86%99%E6%B3%95)。

**Comment by liicos** [comment]
解决了，多谢~ 👍
