### ISSUE TITLE
数据校验的写法是怎样的？

### ISSUE THREAD

**Issue by zhuchongyue** [ecomfe/san-loader#26]
如题，DataTypes在单文件export  {} (非export class）写法中支持么？
支持的话，语法是怎样的？

**Comment by Lohoyo** [comment]
下午好。
支持的，语法和 [san 官方文档](https://baidu.github.io/san/tutorial/data-checking/)的一样，没有特别的地方。
如下所示：

`export default {
    dataTypes: {
        name: DataTypes.string
    }
}`

你会不会是少写了个`default`？
