### ISSUE TITLE
使用 scoped css 时，scoped id 没有作为 attribute 写回 DOM Element。

### ISSUE THREAD

**Issue by Dafrok** [ecomfe/san-loader#5]
## 问题

在使用 .san 组件时，scoped style 生成了一个 id，这个 id 写入了 style 标签，但没有写回这个 style 对应的 DOM Element。

## 复现用例

```html
<template>
<span class="foo">foo</span>
</template>

<style scoped>
.foo {
  display: none;
}
</style>
```

### 期望输出

```html
<style>
.foo[_s_HASH_OF_COMPONENT] { display: none; }
</style>
...
<span class="foo" _s_HASH_OF_COMPONENT>foo</span>
```

### 实际输出

```html
<style>
.foo[_s_HASH_OF_COMPONENT] { display: none; }
</style>
...
<span class="foo">foo</span>
```

**Comment by Dafrok** [comment]
问题追踪到了，不是 san-loader 的问题，是 san 把生成的 scoped id 属性给抹掉了。我去那边发个 issue 吧。

**Comment by teazean** [comment]
san: 3.2.8
san-loader: 0.0.4

问题还是同样。html标签中丢失 scoped id

**Comment by teazean** [comment]
看了下 san-loader的最新发布。。原来是没发新版。。

**Comment by junmer** [comment]
在不大改 loader 的情况下，可以让 san 对 attr 加一下处理，最简单的方式有：

1. data-san-${hashId}=""
```
<div data-san-ef3f12a6=""></div>
```
2. _s-${hashId}=""
```
<div _s-ef3f12a6=""></div>
```
稍微优化一些 parse5 可以

3. data-san-${hashId}
```
<div data-san-ef3f12a6></div>
```
4. _s-${hashId}
```
<div _s-ef3f12a6></div>
```
参考
> https://www.w3.org/TR/2017/REC-html51-20171003/infrastructure.html#sec-boolean-attributes
> https://www.w3.org/TR/2017/REC-html51-20171003/dom.html#element-definitions-attributes


@erik168  怎么看？

**Comment by junmer** [comment]
8dfbe7f5761f2935b5791f6a8e855a46fdf1a739 fixed

**Comment by junmer** [comment]
@teazean @Dafrok 多谢建议
请 结合 `san@3.2.9` 一起服用

**Comment by teazean** [comment]
项目已经写了一大半了，不可能再转向 scoped了。。但是还是给好评~~~
